title: <p align="center"> Ritesh Dubey </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/ritesh-dubey">LinkedIn</a> |
  <a href="https://github.com/ritesd">GitHub</a>
  </p>
  <br>
  <p align="left">
  I am persuning Master in Machine Learning & AI from LJMU and Executive PG programme in ML & AI from IIIT Bangalore.
  Also working as Senior Software Engineer at Hypersonix.ai.
  </p>
  <p>
  <h4 align="left">Skills:</h3>
  <small>
  python, SQL, Unix Command and Shell Scripting, selenium
  web driver, Django framework, JavaScript, Node.js, Docker,
  sentry, Redis
  </small>
  </p>

theme: jekyll-theme-minimal